#!/bin/sh
#
# @name tg_ag
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Liang Peng
#
#

sh /etc/init.d/rc.mc_defaults
set MIXER quad_mockup
set PWM_OUT 1234

#
# Load default params for this platform
#
if [ $AUTOCNF == yes ]
then
	# Set all params here, then disable autoconfig

	param set BAT_N_CELLS 3

	param set EKF2_AID_MASK 2
	param set EKF2_RNG_AID 1

	param set PWM_MIN 1030
	param set PWM_MAX 1950

	param set COM_FLTMODE1 0
	param set COM_FLTMODE4 1
	param set COM_FLTMODE6 2

	param set SDLOG_PROFILE 83

	param set MPC_HOLD_DZ 0.15

	# PID tuning
	param set MC_ROLLRATE_P 0.08
	param set MC_ROLLRATE_I 0.25
	param set MC_ROLLRATE_D 0.001
	param set MC_ROLL_P 8

	param set MC_PITCHRATE_P 0.08
	param set MC_PITCHRATE_I 0.25
	param set MC_PITCHRATE_D 0.001
	param set MC_PITCH_P 8

	param set MC_YAWRATE_P 0.25
	param set MC_YAWRATE_I 0.3
	param set MC_YAW_P 4

	param set MPC_THR_HOVER 0.6

	# sensors
	param set SENS_EN_PAW3902 1
	param set SENS_TFMINI_CFG 104

	param set SYS_USE_IO 0
fi



